#%RAML 1.0

title: Jungle Devs - Django Challenge-001
version: v1
baseUri: http://localhost
mediaType:  application/json

traits:
  secured:
    usage: Apply this to any method that needs to be secured
    description: Some requests require authentication.
    headers:
      Authorization:
        description: Access Token
        example: Token ca7eab006374b95c515cb16f9c7fb5004d8467b2
        required: true

types:
  User:
    description: API user.
    properties:
      username:
      password:
    example:
      username: bob
      password: "123456"

  AccessToken:
    description: |
        Token returned from the server if authentication is OK,
        it must be used to access administrator content.
    properties:
      token:
        type: string
    example:
      token: ca7eab006374b95c515cb16f9c7fb5004d8467b2

  Message:
    description: Informative messages.
    properties:
      message: string

/api/login:
  description: Users authentication.
  post:
    body:
      type: User
    responses:
      200:
        body:
          type: AccessToken

      400:
        body:
          type: Message
          example:
            message: Unable to log in with provided credentials.

/api/sign-up:
  description: Create new users.
  post:
    body:
      type: User
    responses:
      201:
        description: New user created successfully.
        body:
          example:
            username: bob
            password: pbkdf2_sha256$216000$FaNpgFroPRPz$xzmqigb8tX51GRRULE6a6S/S0lcfVORsYLTyJCzDAN4=
      400:
        body:
          type: Message
          example:
            message: A user with that username already exists.

/api/admin/authors:
  is: [secured]
  post:
    body:
      type: object
      properties:
        name:
        picture:
      example:
        name: John Doe
        picture: http://johndoepic.com
    responses:
      201:
        description: Author created successfully.
        body:
          type: object
          properties:
            id:
            name:
            picture:
          example:
            id: 2d460e48-a4fa-370b-a2d0-79f2f601988c
            name: John Doe
            picture: http://johndoepic.com
      400:
        description: A valid URL is mandatory.
        body:
          type: Message
          example:
            message: Enter a valid URL.
      401:
        body:
          type: Message
          example:
            message: Authentication credentials were not provided.
  get:
    description: Retrieve a list of all authors.
    responses:
      200:
        body:
          type: array
          example:
            - # item 1
              id: 2d460e48-a4fa-370b-a2d0-79f2f601988c
              name: John Doe
              picture: http://johndoepic.com
            - # item 2
              id: 32160e48-a4fa-370b-a2d0-79f2f601988c
              name: Jane Doe
              picture: http://janedoepic.com
      401:
        body:
          type: Message
          example:
            message: Authentication credentials were not provided.

  /{author_id}:
    is: [secured]
    uriParameters:
      author_id: string
    get:
      description: Retrieve infomation of an author with the respective id.
      responses:
        200:
          body:
            type: object
            properties:
              id:
              name:
              picture:
            example:
              id: 2d460e48-a4fa-370b-a2d0-79f2f601988c
              name: John Doe
              picture: http://johndoepic.com
        404:
          body:
            type: Message
            example:
              message: Not found.
        401:
          body:
            type: Message
            example:
              message: Authentication credentials were not provided.

    put:
      description: Update the author information with the respective id.
      body:
        type: object
        properties:
          name?:
          picture?:
        example:
          name: John Doe Updated
          picture: https://newjohndoepic.com
      responses:
        200:
          body:
            type: object
            example:
              id: 2d460e48-a4fa-370b-a2d0-79f2f601988c
              name: John Doe Updated
              picture: https://newjohndoepic.com
        404:
          body:
            type: Message
            example:
              message: Not found.
        401:
          body:
            type: Message
            example:
              message: Authentication credentials were not provided.

    delete:
      description: Delete the author with the respective id.
      responses:
        204:
          description: Author deleted successfully.
        404:
          body:
            type: Message
            example:
              message: Not found.
        401:
          body:
            type: Message
            example:
              message: Authentication credentials were not provided.

/api/admin/articles:
  is: [secured]
  post:
    description: Create a new article.
    body:
      type: object
      properties:
        author:
        category:
        title:
        summary:
        first_paragraph:
        body:
      example:
        author: 2d460e48-a4fa-370b-a2d0-79f2f601988c
        category: science fiction
        title: "2001: A Space Odyssey"
        summary: "2001: A Space Odyssey is..."
        first_paragraph: In the prehistoric African veldt, a tribe of hominids is driven away from...
        body: Millions of years later, Dr. Heywood Floyd...
    responses:
      201:
        description: Article created successfully.
        body:
          type: object
          example:
            author: 2d460e48-a4fa-370b-a2d0-79f2f601988c
            category: science fiction
            title: "2001: A Space Odyssey"
            summary: "2001: A Space Odyssey is..."
            first_paragraph: In the prehistoric African veldt, a tribe of hominids is driven away from...
            body: Millions of years later, Dr. Heywood Floyd...
      400:
        description: Author ID not found.
        body:
          type: Message
          example:
            message: Invalid pk fc55f5cd-f239-4e4e-885d-7a02654d51a9 - object does not exist.
      401:
        body:
          type: Message
          example:
            message: Authentication credentials were not provided.
  get:
    description: Retrieve a list with all articles.
    responses:
      200:
        description: List of all articles
        body:
          type: array
          example:
            - # item 1
              id: abc60e48-a4fa-370b-a2d0-79f2f601988c
              author: 2d460e48-a4fa-370b-a2d0-79f2f601988c
              category: science fiction
              title: "2001: A Space Odyssey"
              summary: "2001: A Space Odyssey is..."
              first_paragraph: In the prehistoric African veldt, a tribe of hominids is driven away from...
              body: Millions of years later, Dr. Heywood Floyd...
            - # item 2
              id: def60e48-a4fa-370b-a2d0-79f2f601988c
              author: 12345e48-a4fa-370b-a2d0-79f2f601988c
              category: drama
              title: "Pride and Prejudice"
              summary: Pride and Prejudice is an 1813 romantic novel of manners written by Jane Austen...
              first_paragraph: The novel is set in rural England in the early 19th century...
              body: At the ball, we are first introduced to the whole Netherfield party, which...
      401:
        body:
          type: Message
          example:
            message: Authentication credentials were not provided.

  /{article_id}:
    is: [secured]
    uriParameters:
      article_id: string
    get:
      description: Retrieve infomation of an article with the respective id.
      responses:
        200:
          body:
            type: object
            example:
              author_id: 2d460e48-a4fa-370b-a2d0-79f2f601988c
              category: science fiction
              title: "2001: A Space Odyssey"
              summary: "2001: A Space Odyssey is..."
              first_paragraph: In the prehistoric African veldt, a tribe of hominids is driven away from...
              body: Millions of years later, Dr. Heywood Floyd...
        404:
          description: Article id not found.
          body:
            type: Message
            example:
              message: Not found.
        401:
          body:
            type: Message
            example:
              message: Authentication credentials were not provided.
    put:
      description: Update the article information with the respective id.
      body:
        type: object
        properties:
          author?:
          category?:
          title?:
          summary?:
          first_paragraph?:
          body?:
        example:
          title: "2001: A Space Odyssey Updated"
          summary: "2001: A Space Odyssey is... more info"
      responses:
        200:
          description: Article successfully updated.
          body:
            type: object
            example:
              id: 2d460e48-a4fa-370b-a2d0-79f2f6aaaaa
              author: 2d460e48-a4fa-370b-a2d0-79f2f601988c
              category: science fiction
              title: "2001: A Space Odyssey Updated"
              summary: "2001: A Space Odyssey is... more info"
              first_paragraph: In the prehistoric African veldt, a tribe of hominids is driven away from...
              body: Millions of years later, Dr. Heywood Floyd...
        400:
          description: Some parameter is not ok.
          body:
            type: Message
            example:
              message: invalid-id is not a valid UUID.
        404:
          description: Article id not found.
          body:
            type: Message
            example:
              message: Not found.
        401:
          body:
            type: Message
            example:
              message: Authentication credentials were not provided.
    delete:
      description: Delete the article information with the respective id.
      responses:
        204:
          description: Article successfully deleted.
        404:
          description: Article id not found.
          body:
            type: Message
            example:
              message: Not found.
        401:
          body:
            type: Message
            example:
              message: Authentication credentials were not provided.

/api/articles:
  get:
    description: Get a list of articles.
    queryParameters:
      category?:
        description: Category slug
        type: string
        example: science-fiction

  /{article_id}:
    description: Detailed information of an article.
    uriParameters:
      article_id:
    get:
      description: The detail level will depend on it's a logged or anonymous user.
      responses:
        200:
          body:
            type: object
            examples:
              logged_user:
                id: 2d460e48-a4fa-370b-a2d0-79f2f601988c
                author:
                  id: 2d460e48-a4fa-370b-a2d0-79f2f601988c
                  name: Author Name
                  picture: https://picture.url
                category: science fiction
                title: "2001: A Space Odyssey Updated"
                summary: "2001: A Space Odyssey is... more info"
                first_paragraph: In the prehistoric African veldt, a tribe of hominids is driven away from...
                body: Millions of years later, Dr. Heywood Floyd...
              anonymous_user:
                id: 2d460e48-a4fa-370b-a2d0-79f2f601988c
                author:
                  id: 2d460e48-a4fa-370b-a2d0-79f2f601988c
                  name: Author Name
                  picture: https://picture.url
                category: science fiction
                title: "2001: A Space Odyssey Updated"
                summary: "2001: A Space Odyssey is... more info"
                first_paragraph: In the prehistoric African veldt, a tribe of hominids is driven away from...
        404:
          description: Article id not found.
          body:
            type: Message
            example:
              message: Not found.
