version: '3.0'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; gunicorn --bind 0.0.0.0:8000 news_api.wsgi'
    ports:
      - 8008:8000
    environment:
      - POSTGRES_URL=db
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=challenge
      - POSTGRES_DB=challenge

volumes:
  postgres_data_prod:
